# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install yarn
        run: npm install -g yarn
        shell: bash

      - name: Install packages
        run: yarn
        shell: bash

      - name: Build
        run: yarn build
        shell: bash

      - name: Test
        run: yarn test
        shell: bash

      - name: Publish
        run: yarn release
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
